### ISSUE TITLE
Please publish the status of this project

### ISSUE THREAD

**Issue by ArsenShnurkov** [prepare/CsQuery#3]
Is upstream unresponsive to pull requests? Why you don't sync state be providing pull requests to it? Will you release your version? Which stable commit to use?

**Comment by prepare** [comment]
My fork is in study/ analysis phase,
so there are many bugs
because I try to separate them into smaller modules ( eg. Dom, DomBuilder etc)
so I'm afraid that its too early to collab with the original one.

it's not ready to use :)
